# Generated by Django 5.1.2 on 2024-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BRAZIL', 'Brasil'), ('USA', 'Estados Unidos'), ('GERMANY', 'Alemanha'), ('ENGLAND', 'Inglaterra'), ('JAPAN', 'Japão'), ('CHINA', 'China')], max_length=100, null=True)),
            ],
        ),
    ]
